// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAutoLink = `-- name: CreateAutoLink :one
INSERT INTO links (code, target_url, expires_at, auto_dedup)
VALUES ($1, $2, NULL, true)
ON CONFLICT (target_url)
WHERE auto_dedup = true AND expires_at IS NULL AND deleted_at IS NULL
DO UPDATE SET code = links.code
RETURNING id, code, target_url, created_at, click_count, expires_at, deleted_at, auto_dedup
`

type CreateAutoLinkParams struct {
	Code      string
	TargetUrl string
}

func (q *Queries) CreateAutoLink(ctx context.Context, arg CreateAutoLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createAutoLink, arg.Code, arg.TargetUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TargetUrl,
		&i.CreatedAt,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.DeletedAt,
		&i.AutoDedup,
	)
	return i, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (code, target_url, expires_at)
VALUES ($1, $2, $3)
RETURNING id, code, target_url, created_at, click_count, expires_at, deleted_at, auto_dedup
`

type CreateLinkParams struct {
	Code      string
	TargetUrl string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Code, arg.TargetUrl, arg.ExpiresAt)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TargetUrl,
		&i.CreatedAt,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.DeletedAt,
		&i.AutoDedup,
	)
	return i, err
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT id, code, target_url, created_at, click_count, expires_at, deleted_at, auto_dedup
FROM links
WHERE code = $1
`

func (q *Queries) GetLinkByCode(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCode, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TargetUrl,
		&i.CreatedAt,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.DeletedAt,
		&i.AutoDedup,
	)
	return i, err
}

const getLinkByTargetURL = `-- name: GetLinkByTargetURL :one
SELECT id, code, target_url, created_at, click_count, expires_at, deleted_at, auto_dedup
FROM links
WHERE target_url = $1
  AND expires_at IS NULL
  AND deleted_at IS NULL
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetLinkByTargetURL(ctx context.Context, targetUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByTargetURL, targetUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TargetUrl,
		&i.CreatedAt,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.DeletedAt,
		&i.AutoDedup,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE links SET click_count = click_count + 1 WHERE code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, incrementClicks, code)
	return err
}

const listLinks = `-- name: ListLinks :many
SELECT id, code, target_url, created_at, click_count, expires_at, deleted_at, auto_dedup
FROM links
WHERE deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListLinks(ctx context.Context, limit int32) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TargetUrl,
			&i.CreatedAt,
			&i.ClickCount,
			&i.ExpiresAt,
			&i.DeletedAt,
			&i.AutoDedup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksBeforeID = `-- name: ListLinksBeforeID :many
SELECT id, code, target_url, created_at, click_count, expires_at, deleted_at, auto_dedup
FROM links
WHERE id < $1
  AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY id DESC
LIMIT $2
`

type ListLinksBeforeIDParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ListLinksBeforeID(ctx context.Context, arg ListLinksBeforeIDParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksBeforeID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TargetUrl,
			&i.CreatedAt,
			&i.ClickCount,
			&i.ExpiresAt,
			&i.DeletedAt,
			&i.AutoDedup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLink = `-- name: SoftDeleteLink :execresult
UPDATE links
SET deleted_at = now()
WHERE code = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLink(ctx context.Context, code string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, softDeleteLink, code)
}
