// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID         int64
	Code       string
	TargetUrl  string
	CreatedAt  pgtype.Timestamptz
	ClickCount int64
	ExpiresAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	AutoDedup  bool
}
