package handlers_test

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/labstack/echo/v5"

	"github.com/vancanhuit/url-shortener/internal/handlers"
	"github.com/vancanhuit/url-shortener/internal/store"
)

// --- fakes ------------------------------------------------------------------

// fakeStore implements handlers.LinkStore against an in-memory map. It also
// records inserts so the auto-collision retry test can force collisions.
type fakeStore struct {
	mu      sync.Mutex
	links   map[string]store.Link
	nextID  int64
	failNew error // non-nil makes the next CreateLink return failNew
}

func newFakeStore() *fakeStore {
	return &fakeStore{links: map[string]store.Link{}, nextID: 1}
}

func (f *fakeStore) CreateLink(_ context.Context, _ store.DBTX, code, target string) (store.Link, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.failNew != nil {
		err := f.failNew
		f.failNew = nil
		return store.Link{}, err
	}
	if _, ok := f.links[code]; ok {
		return store.Link{}, store.ErrCodeTaken
	}
	l := store.Link{ID: f.nextID, Code: code, TargetURL: target, CreatedAt: time.Unix(0, 0).UTC()}
	f.nextID++
	f.links[code] = l
	return l, nil
}

func (f *fakeStore) GetLinkByCode(_ context.Context, _ store.DBTX, code string) (store.Link, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if l, ok := f.links[code]; ok {
		return l, nil
	}
	return store.Link{}, store.ErrNotFound
}

// fakeCache implements handlers.LinkCache against an in-memory map. TTL is
// recorded but not enforced -- the handler tests don't exercise expiry.
type fakeCache struct {
	mu     sync.Mutex
	values map[string]string
	ttls   map[string]time.Duration
	gets   int
	sets   int
}

func newFakeCache() *fakeCache {
	return &fakeCache{values: map[string]string{}, ttls: map[string]time.Duration{}}
}

func (f *fakeCache) Get(_ context.Context, key string) (string, bool, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.gets++
	v, ok := f.values[key]
	return v, ok, nil
}

func (f *fakeCache) Set(_ context.Context, key, value string, ttl time.Duration) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.sets++
	f.values[key] = value
	f.ttls[key] = ttl
	return nil
}

func (f *fakeCache) Del(_ context.Context, keys ...string) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, k := range keys {
		delete(f.values, k)
		delete(f.ttls, k)
	}
	return nil
}

// scriptedGen returns a fixed sequence of codes; useful for forcing the
// collision retry path deterministically.
type scriptedGen struct {
	codes []string
	idx   int
}

func (s *scriptedGen) Generate() (string, error) {
	if s.idx >= len(s.codes) {
		return "", errors.New("scriptedGen: exhausted")
	}
	c := s.codes[s.idx]
	s.idx++
	return c, nil
}

// --- helpers ----------------------------------------------------------------

const baseURL = "https://short.test"

func newHandlerWithCache(t *testing.T, st handlers.LinkStore, cc handlers.LinkCache, gen handlers.Generator) (*echo.Echo, *handlers.Links) {
	t.Helper()
	h := handlers.NewLinks(handlers.LinksConfig{
		Store:     st,
		Cache:     cc,
		Generator: gen,
		BaseURL:   baseURL,
	})
	e := echo.New()
	h.Mount(e)
	return e, h
}

func doJSON(t *testing.T, e *echo.Echo, method, path, body string) (*httptest.ResponseRecorder, []byte) {
	t.Helper()
	req := httptest.NewRequest(method, path, strings.NewReader(body))
	if body != "" {
		req.Header.Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
	}
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)
	out, err := io.ReadAll(rec.Body)
	if err != nil {
		t.Fatalf("read body: %v", err)
	}
	return rec, out
}

func decodeLink(t *testing.T, body []byte) handlers.LinkResponse {
	t.Helper()
	var resp handlers.LinkResponse
	if err := json.Unmarshal(body, &resp); err != nil {
		t.Fatalf("unmarshal LinkResponse: %v (body=%s)", err, string(body))
	}
	return resp
}

func decodeError(t *testing.T, body []byte) handlers.ErrorResponse {
	t.Helper()
	var resp handlers.ErrorResponse
	if err := json.Unmarshal(body, &resp); err != nil {
		t.Fatalf("unmarshal ErrorResponse: %v (body=%s)", err, string(body))
	}
	return resp
}

// --- Create -----------------------------------------------------------------

func TestCreate_AutoGeneratedCodeReturns201WithShortURL(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{codes: []string{"abc1234"}})

	rec, body := doJSON(t, e, http.MethodPost, "/api/v1/links",
		`{"target_url":"https://example.com/long/path"}`)
	if rec.Code != http.StatusCreated {
		t.Fatalf("status = %d, body = %s", rec.Code, string(body))
	}
	resp := decodeLink(t, body)
	if resp.Code != "abc1234" {
		t.Errorf("Code = %q, want abc1234", resp.Code)
	}
	if resp.ShortURL != baseURL+"/r/abc1234" {
		t.Errorf("ShortURL = %q, want %q", resp.ShortURL, baseURL+"/r/abc1234")
	}
	if resp.TargetURL != "https://example.com/long/path" {
		t.Errorf("TargetURL = %q", resp.TargetURL)
	}
	// Cache populated on create so subsequent redirects don't roundtrip the DB.
	if cc.sets != 1 {
		t.Errorf("cache.sets = %d, want 1", cc.sets)
	}
}

func TestCreate_UserSuppliedCodeIsAcceptedAndPersisted(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{codes: []string{"unused"}})

	rec, body := doJSON(t, e, http.MethodPost, "/api/v1/links",
		`{"target_url":"https://example.com","code":"my-code-1"}`)
	// "my-code-1" contains a hyphen, which ValidCode rejects -> 422.
	if rec.Code != http.StatusUnprocessableEntity {
		t.Fatalf("status = %d, body = %s", rec.Code, string(body))
	}

	rec, body = doJSON(t, e, http.MethodPost, "/api/v1/links",
		`{"target_url":"https://example.com","code":"mycode1"}`)
	if rec.Code != http.StatusCreated {
		t.Fatalf("status = %d, body = %s", rec.Code, string(body))
	}
	if got := decodeLink(t, body).Code; got != "mycode1" {
		t.Errorf("Code = %q, want mycode1", got)
	}
}

func TestCreate_DuplicateUserSuppliedCodeReturns409(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})

	_, _ = doJSON(t, e, http.MethodPost, "/api/v1/links",
		`{"target_url":"https://example.com","code":"taken1"}`)
	rec, body := doJSON(t, e, http.MethodPost, "/api/v1/links",
		`{"target_url":"https://other.example","code":"taken1"}`)
	if rec.Code != http.StatusConflict {
		t.Fatalf("status = %d, body = %s", rec.Code, string(body))
	}
	if got := decodeError(t, body).Error; got == "" {
		t.Errorf("expected non-empty error message")
	}
}

func TestCreate_RetriesPastAutoGeneratedCollisions(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	// pre-seed the first two codes to force two collisions; third succeeds.
	if _, err := st.CreateLink(context.Background(), nil, "first00", "https://x"); err != nil {
		t.Fatalf("seed: %v", err)
	}
	if _, err := st.CreateLink(context.Background(), nil, "second0", "https://y"); err != nil {
		t.Fatalf("seed: %v", err)
	}
	gen := &scriptedGen{codes: []string{"first00", "second0", "third00"}}
	e, _ := newHandlerWithCache(t, st, cc, gen)

	rec, body := doJSON(t, e, http.MethodPost, "/api/v1/links",
		`{"target_url":"https://example.com"}`)
	if rec.Code != http.StatusCreated {
		t.Fatalf("status = %d, body = %s", rec.Code, string(body))
	}
	if got := decodeLink(t, body).Code; got != "third00" {
		t.Errorf("Code = %q, want third00", got)
	}
	if gen.idx != 3 {
		t.Errorf("generator calls = %d, want 3", gen.idx)
	}
}

func TestCreate_BadInputReturns4xx(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name, body string
		wantStatus int
	}{
		{"invalid_json", `{not json`, http.StatusBadRequest},
		{"missing_target_url", `{}`, http.StatusUnprocessableEntity},
		{"empty_target_url", `{"target_url":""}`, http.StatusUnprocessableEntity},
		{"non_http_scheme", `{"target_url":"ftp://x.example"}`, http.StatusUnprocessableEntity},
		{"no_host", `{"target_url":"http://"}`, http.StatusUnprocessableEntity},
		{"too_long", `{"target_url":"https://x.example/` + strings.Repeat("a", 2100) + `"}`, http.StatusUnprocessableEntity},
		{"bad_user_code", `{"target_url":"https://x.example","code":"!!!"}`, http.StatusUnprocessableEntity},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			st, cc := newFakeStore(), newFakeCache()
			e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{codes: []string{"unused0"}})
			rec, _ := doJSON(t, e, http.MethodPost, "/api/v1/links", tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d", rec.Code, tt.wantStatus)
			}
		})
	}
}

// --- Get --------------------------------------------------------------------

func TestGet_ReturnsLinkJSON(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	if _, err := st.CreateLink(context.Background(), nil, "fixed01", "https://example.com"); err != nil {
		t.Fatalf("seed: %v", err)
	}
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})

	rec, body := doJSON(t, e, http.MethodGet, "/api/v1/links/fixed01", "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, body = %s", rec.Code, string(body))
	}
	resp := decodeLink(t, body)
	if resp.Code != "fixed01" {
		t.Errorf("Code = %q", resp.Code)
	}
	if resp.ShortURL != baseURL+"/r/fixed01" {
		t.Errorf("ShortURL = %q", resp.ShortURL)
	}
}

func TestGet_UnknownCodeReturns404(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})
	rec, _ := doJSON(t, e, http.MethodGet, "/api/v1/links/missing", "")
	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want 404", rec.Code)
	}
}

func TestGet_InvalidCodeReturns404(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})
	rec, _ := doJSON(t, e, http.MethodGet, "/api/v1/links/aa", "") // < MinLength
	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want 404", rec.Code)
	}
}

// --- Redirect ---------------------------------------------------------------

func TestRedirect_HitsCacheWithoutTouchingStore(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	if err := cc.Set(context.Background(), "link:cached1", "https://cached.example", time.Minute); err != nil {
		t.Fatalf("seed cache: %v", err)
	}
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})

	req := httptest.NewRequest(http.MethodGet, "/r/cached1", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)
	if rec.Code != http.StatusFound {
		t.Fatalf("status = %d", rec.Code)
	}
	if loc := rec.Header().Get("Location"); loc != "https://cached.example" {
		t.Errorf("Location = %q", loc)
	}
	if cc.gets != 1 {
		t.Errorf("cache.gets = %d, want 1", cc.gets)
	}
}

func TestRedirect_FallsBackToStoreAndBackfillsCache(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	if _, err := st.CreateLink(context.Background(), nil, "fromdb1", "https://db.example"); err != nil {
		t.Fatalf("seed: %v", err)
	}
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})

	req := httptest.NewRequest(http.MethodGet, "/r/fromdb1", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)
	if rec.Code != http.StatusFound {
		t.Fatalf("status = %d", rec.Code)
	}
	if loc := rec.Header().Get("Location"); loc != "https://db.example" {
		t.Errorf("Location = %q", loc)
	}
	if got := cc.values["link:fromdb1"]; got != "https://db.example" {
		t.Errorf("cache backfill missing: %q", got)
	}
}

func TestRedirect_UnknownCodeReturns404(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})
	req := httptest.NewRequest(http.MethodGet, "/r/missing", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)
	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want 404", rec.Code)
	}
}

func TestRedirect_InvalidCodeReturns404(t *testing.T) {
	t.Parallel()
	st, cc := newFakeStore(), newFakeCache()
	e, _ := newHandlerWithCache(t, st, cc, &scriptedGen{})
	req := httptest.NewRequest(http.MethodGet, "/r/aa", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)
	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want 404", rec.Code)
	}
}
