// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseCode.
const (
	ErrorResponseCodeCodeTaken        ErrorResponseCode = "code_taken"
	ErrorResponseCodeInternalError    ErrorResponseCode = "internal_error"
	ErrorResponseCodeInvalidJSONBody  ErrorResponseCode = "invalid_json_body"
	ErrorResponseCodeLinkDeleted      ErrorResponseCode = "link_deleted"
	ErrorResponseCodeLinkExpired      ErrorResponseCode = "link_expired"
	ErrorResponseCodeNotFound         ErrorResponseCode = "not_found"
	ErrorResponseCodeRateLimited      ErrorResponseCode = "rate_limited"
	ErrorResponseCodeValidationFailed ErrorResponseCode = "validation_failed"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case ErrorResponseCodeCodeTaken:
		return true
	case ErrorResponseCodeInternalError:
		return true
	case ErrorResponseCodeInvalidJSONBody:
		return true
	case ErrorResponseCodeLinkDeleted:
		return true
	case ErrorResponseCodeLinkExpired:
		return true
	case ErrorResponseCodeNotFound:
		return true
	case ErrorResponseCodeRateLimited:
		return true
	case ErrorResponseCodeValidationFailed:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Stable machine-readable identifier for client-side
	// branching. Once published, values do not change; new
	// codes may be added.
	Code ErrorResponseCode `json:"code"`

	// Error Human-readable description, safe to surface in a UI.
	Error string `json:"error"`
}

// ErrorResponseCode Stable machine-readable identifier for client-side
// branching. Once published, values do not change; new
// codes may be added.
type ErrorResponseCode string

// LinkRequest defines model for LinkRequest.
type LinkRequest struct {
	// Code Optional user-supplied short code. When omitted, the
	// server generates one. Only base62 characters are
	// allowed; supplying a code opts out of dedup.
	Code *string `json:"code,omitempty"`

	// ExpiresAt Optional RFC 3339 expiry. Must be in the future (a 30s
	// grace window absorbs honest clock skew). Supplying an
	// expiry opts out of dedup. Omit (or send `null`) for a
	// permanent link.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// TargetURL The destination URL. Must be `http` or `https` with a
	// non-empty host; max 2048 characters.
	TargetURL string `json:"target_url"`
}

// LinkResponse defines model for LinkResponse.
type LinkResponse struct {
	// ClickCount Lifetime hit count for `/r/{code}`. Eventually-consistent:
	// increments are applied fire-and-forget so a freshly-served
	// redirect may not be reflected in the next response.
	ClickCount int64     `json:"click_count"`
	Code       string    `json:"code"`
	CreatedAt  time.Time `json:"created_at"`

	// ExpiresAt RFC 3339 expiry. Omitted entirely (rather than rendered
	// as `null`) for permanent links, so a one-key check
	// distinguishes them.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// ShortURL The fully-qualified short URL (`{base_url}/r/{code}`).
	ShortURL  string `json:"short_url"`
	TargetURL string `json:"target_url"`
}

// ListResponse defines model for ListResponse.
type ListResponse struct {
	// Items Links on this page, ordered newest-first.
	Items []LinkResponse `json:"items"`

	// NextCursor Opaque cursor for the next page. Pass it back as the
	// `before` query parameter; `null` on the last page.
	NextCursor *int64 `json:"next_cursor"`
}

// Code defines model for Code.
type Code = string

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListLinksParams defines parameters for ListLinks.
type ListLinksParams struct {
	// Limit Page size. Defaults to 10. Values above 100 are silently
	// clamped down. Non-positive or non-numeric values fall back
	// to the default.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before Exclusive lower bound on the row id; pass the previous
	// page's `next_cursor` to walk backwards in time. Omit (or
	// pass `0`) for the first page.
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`
}

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody = LinkRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List recent links.
	// (GET /api/v1/links)
	ListLinks(w http.ResponseWriter, r *http.Request, params ListLinksParams)
	// Create a short link.
	// (POST /api/v1/links)
	CreateLink(w http.ResponseWriter, r *http.Request)
	// Soft-delete a link.
	// (DELETE /api/v1/links/{code})
	DeleteLink(w http.ResponseWriter, r *http.Request, code Code)
	// Fetch link metadata.
	// (GET /api/v1/links/{code})
	GetLink(w http.ResponseWriter, r *http.Request, code Code)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List recent links.
// (GET /api/v1/links)
func (_ Unimplemented) ListLinks(w http.ResponseWriter, r *http.Request, params ListLinksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a short link.
// (POST /api/v1/links)
func (_ Unimplemented) CreateLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a link.
// (DELETE /api/v1/links/{code})
func (_ Unimplemented) DeleteLink(w http.ResponseWriter, r *http.Request, code Code) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch link metadata.
// (GET /api/v1/links/{code})
func (_ Unimplemented) GetLink(w http.ResponseWriter, r *http.Request, code Code) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLinks operation middleware
func (siw *ServerInterfaceWrapper) ListLinks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLinksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLinks(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLink operation middleware
func (siw *ServerInterfaceWrapper) CreateLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLink(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLink operation middleware
func (siw *ServerInterfaceWrapper) DeleteLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code Code

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLink(w, r, code)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLink operation middleware
func (siw *ServerInterfaceWrapper) GetLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code Code

	err = runtime.BindStyledParameterWithOptions("simple", "code", chi.URLParam(r, "code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLink(w, r, code)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/links", wrapper.ListLinks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/links", wrapper.CreateLink)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/links/{code}", wrapper.DeleteLink)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/links/{code}", wrapper.GetLink)
	})

	return r
}

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ListLinksRequestObject struct {
	Params ListLinksParams
}

type ListLinksResponseObject interface {
	VisitListLinksResponse(w http.ResponseWriter) error
}

type ListLinks200JSONResponse ListResponse

func (response ListLinks200JSONResponse) VisitListLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLinks500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListLinks500JSONResponse) VisitListLinksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLinkRequestObject struct {
	Body *CreateLinkJSONRequestBody
}

type CreateLinkResponseObject interface {
	VisitCreateLinkResponse(w http.ResponseWriter) error
}

type CreateLink200JSONResponse LinkResponse

func (response CreateLink200JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLink201JSONResponse LinkResponse

func (response CreateLink201JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLink400JSONResponse ErrorResponse

func (response CreateLink400JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLink409JSONResponse ErrorResponse

func (response CreateLink409JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLink422JSONResponse ErrorResponse

func (response CreateLink422JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLink429JSONResponse ErrorResponse

func (response CreateLink429JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLink500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateLink500JSONResponse) VisitCreateLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteLinkRequestObject struct {
	Code Code `json:"code"`
}

type DeleteLinkResponseObject interface {
	VisitDeleteLinkResponse(w http.ResponseWriter) error
}

type DeleteLink204Response struct {
}

func (response DeleteLink204Response) VisitDeleteLinkResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteLink404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteLink404JSONResponse) VisitDeleteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteLink500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteLink500JSONResponse) VisitDeleteLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetLinkRequestObject struct {
	Code Code `json:"code"`
}

type GetLinkResponseObject interface {
	VisitGetLinkResponse(w http.ResponseWriter) error
}

type GetLink200JSONResponse LinkResponse

func (response GetLink200JSONResponse) VisitGetLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLink404JSONResponse struct{ NotFoundJSONResponse }

func (response GetLink404JSONResponse) VisitGetLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetLink410JSONResponse ErrorResponse

func (response GetLink410JSONResponse) VisitGetLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type GetLink500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetLink500JSONResponse) VisitGetLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List recent links.
	// (GET /api/v1/links)
	ListLinks(ctx context.Context, request ListLinksRequestObject) (ListLinksResponseObject, error)
	// Create a short link.
	// (POST /api/v1/links)
	CreateLink(ctx context.Context, request CreateLinkRequestObject) (CreateLinkResponseObject, error)
	// Soft-delete a link.
	// (DELETE /api/v1/links/{code})
	DeleteLink(ctx context.Context, request DeleteLinkRequestObject) (DeleteLinkResponseObject, error)
	// Fetch link metadata.
	// (GET /api/v1/links/{code})
	GetLink(ctx context.Context, request GetLinkRequestObject) (GetLinkResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListLinks operation middleware
func (sh *strictHandler) ListLinks(w http.ResponseWriter, r *http.Request, params ListLinksParams) {
	var request ListLinksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLinks(ctx, request.(ListLinksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLinks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLinksResponseObject); ok {
		if err := validResponse.VisitListLinksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateLink operation middleware
func (sh *strictHandler) CreateLink(w http.ResponseWriter, r *http.Request) {
	var request CreateLinkRequestObject

	var body CreateLinkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLink(ctx, request.(CreateLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateLinkResponseObject); ok {
		if err := validResponse.VisitCreateLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteLink operation middleware
func (sh *strictHandler) DeleteLink(w http.ResponseWriter, r *http.Request, code Code) {
	var request DeleteLinkRequestObject

	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLink(ctx, request.(DeleteLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteLinkResponseObject); ok {
		if err := validResponse.VisitDeleteLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLink operation middleware
func (sh *strictHandler) GetLink(w http.ResponseWriter, r *http.Request, code Code) {
	var request GetLinkRequestObject

	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLink(ctx, request.(GetLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLinkResponseObject); ok {
		if err := validResponse.VisitGetLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
